In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Many-to-one merge situation
# Many-to-many merges
# One-to-one merges

# Merge on common cols name: on='key'
# Merge on dif cols names: left_on='cow', right_on='bull'
# Merge on index: both df have the same type of values in the index col: left_index=True, right_index=True
# Merge on index: dfs have dif values in the index col: left_on='key', right_index=True
# Mixed merge:

In [2]:
# many-to-one merge situation: df2 has only one 'a', one 'b' and one 'd'

df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
'data1': range(7)})

In [3]:
df2 = DataFrame({'key': ['a', 'b', 'd'],
'data2': range(3)})

In [5]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [6]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [5]:
pd.merge(df1, df2, on='key')
#c and d are excluded (merge is in fact an inner join)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [11]:
#if keys have different name:
# same example with dif names of the keys:

df3 = DataFrame({'cow': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
'data1': range(7)})

In [12]:
df4 = DataFrame({'bull': ['a', 'b', 'd'],
'data2': range(3)})

In [13]:
pd.merge(df3, df4, left_on='cow', right_on='bull') # d and c are again out

cow  data1 bull  data2
0   b      0    b      1
1   b      1    b      1
2   b      6    b      1
3   a      2    a      0
4   a      4    a      0
5   a      5    a      0

In [42]:
# Many-to-many merges: df6 has several 'a' and 'b'

df5 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
'data1': range(6)});

df6 = DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],
'data2': range(5)});


In [19]:
pd.merge(df5, df6, on='key', how='left') 
#Cartesian product of the rows, so 3 'b' in the left and 2 'b'
# in the right  = 6 'b' 
# 'd' is out coz not in the left df

data1 key  data2
0       0   b    1.0
1       0   b    3.0
2       1   b    1.0
3       1   b    3.0
4       2   a    0.0
5       2   a    2.0
6       3   c    NaN
7       4   a    0.0
8       4   a    2.0
9       5   b    1.0
10      5   b    3.0

In [21]:
pd.merge(df5, df6, on='key', how='inner') 
# here 'c' is also out, but again  6 'b'

data1 key  data2
0      0   b      1
1      0   b      3
2      1   b      1
3      1   b      3
4      5   b      1
5      5   b      3
6      2   a      0
7      2   a      2
8      4   a      0
9      4   a      2

In [22]:
#To merge with multiple keys, pass a list of column names:

left = DataFrame({'key1': ['foo', 'foo', 'bar'],
                  'key2': ['one', 'two', 'one'],
                  'lval': [1, 2, 3]});

right = DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'rval': [4, 5, 6, 7]});

print(left)
print(right)

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3
  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7


In [24]:
pd.merge(left, right, on=['key1', 'key2'], how='left')

key1 key2  lval  rval
0  foo  one     1   4.0
1  foo  one     1   5.0
2  foo  two     2   NaN
3  bar  one     3   6.0

In [28]:
pd.merge(left, right, on=['key1', 'key2'], how='inner')

key1 key2  lval  rval
0  foo  one     1     4
1  foo  one     1     5
2  bar  one     3     6

In [28]:
# Merging on Index:

staff_df = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR'},
                         {'Name': 'Sally', 'Role': 'Course liasion'},
                         {'Name': 'James', 'Role': 'Grader'}])
staff_df = staff_df.set_index('Name')
student_df = pd.DataFrame([{'Name': 'James', 'School': 'Business'},
                           {'Name': 'Mike', 'School': 'Law'},
                           {'Name': 'Sally', 'School': 'Engineering'}])
student_df = student_df.set_index('Name')

print(staff_df.head())
print()
print(student_df.head())

                 Role
Name                 
Kelly  Director of HR
Sally  Course liasion
James          Grader
()
            School
Name              
James     Business
Mike           Law
Sally  Engineering


In [30]:
# both df have the same type of values in the index col

pd.merge(staff_df, student_df, how='outer', left_index=True, 
         right_index=True)

# left_index=True: use index as key

Role       School
Name                              
James          Grader     Business
Kelly  Director of HR          NaN
Mike              NaN          Law
Sally  Course liasion  Engineering

In [25]:
# dfs have dif types of indexes, one default numbers, 
# the second categ. 

left1 = DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                   'value': range(6)})

right1 = DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

print(left1)
print(right1)
    

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5
   group_val
a        3.5
b        7.0


In [38]:
pd.merge(left1, right1, left_on='key', right_index=True) 

# left_on: use vals in 'key' col as key
# right_index: Use row index in right DF as its join key (here
# there is no name for the index so 'right_index=True' is used)
# if the indexes in both DF were exactly the same then: 
# 'left_index=True, right_index=True' 


key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [40]:
pd.merge(left1, right1, left_on='key', right_index=True, how='left')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [41]:
# CONCATINATION.

arr = np.arange(12).reshape((3, 4));
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
np.concatenate([arr, arr]) # concat by rows

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
np.concatenate([arr, arr], axis=1) # concat by columns

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [45]:
# Series and DF

s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])

In [46]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [47]:
pd.concat([s1,s2,s3], axis=1) # result is a DF

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0